export const Blogs = [
  {
    slug: "scaling-saas-products",
    title: "Scaling SaaS Products in 2025",
    desc: "Discover the architecture patterns, cloud scalability techniques, and CI/CD pipelines we used to build SaaS platforms that handle millions of users. Learn how to structure your services, optimize performance, and implement scalable microservices for long-term growth.",
    image: "/blog/cba.png",
    category: "SaaS",
    author: "Team Maldonite",
    date: "Aug 1, 2025",
  },
  {
    slug: "seo-strategies-2025",
    title: "Modern SEO Strategies That Work",
    desc: "Explore cutting-edge SEO strategies that are dominating 2025—from semantic search and Google's AI-driven ranking systems to high-performing keyword clustering, E-E-A-T improvements, and advanced link-building outreach techniques. These data-driven tactics help you outrank competitors and grow organic traffic.",
    image: "/blog/mohit.png",
    category: "SEO",
    author: "Team Maldonite",
    date: "Jul 24, 2025",
  },
  {
    slug: "product-roadmapping-strategies",
    title: "How to Build an Effective Product Roadmap",
    desc: "A great product roadmap aligns your team, stakeholders, and users around a clear vision. In this blog, we share real-world frameworks for prioritizing features, handling trade-offs, and maintaining flexibility. Learn how to balance short-term wins with long-term strategy while ensuring engineering feasibility and customer impact.",
    image: "/blog/neha.png",
    category: "Product",
    author: "Sandeep Saini",
    date: "Aug 2, 2025",
  },
  {
    slug: "mvp-to-scalable-product",
    title: "From MVP to Scalable Product: Lessons Learned",
    desc: "Building an MVP is easy—scaling it is the hard part. In this post, we explore how to transition from a scrappy prototype to a robust, market-ready product. Learn from our experience with technical debt, refactoring decisions, feature creep control, and user-driven iteration that helped us turn our MVP into a successful SaaS platform.",
    image: "/blog/rahul.png",
    category: "Product",
    author: "Team Maldonite",
    date: "Jul 26, 2025",
  },
  {
    slug: "ai-integration-guide",
    title: "AI Integrations in Web Apps",
    desc: "Integrating AI into your SaaS has never been easier. We walk you through implementing OpenAI APIs for chat, OCR for document parsing, and NLP for sentiment analysis. Build intelligent apps that adapt to user behavior, automate workflows, and offer smarter UX experiences.",
    image: "/blog/rahul.png",
    category: "AI",
    author: "Team Ignot",
    date: "Jul 4, 2025",
  },
  {
    slug: "ux-for-saas",
    title: "Designing Intuitive UX for SaaS Platforms",
    desc: "Good design drives engagement. This article explores UX principles specific to SaaS—like progressive disclosure, contextual guidance, and visual hierarchy—to help teams create intuitive, scalable interfaces that users love.",
    image: "/blog/neha.png",
    category: "UI/UX",
    author: "Team Ignot",
    date: "Jun 20, 2025",
  },
  {
    slug: "building-devtools",
    title: "Building Developer Tools That Scale",
    desc: "We reveal how we built powerful internal tools that boosted productivity across engineering teams. Learn how to create devtools with clean DX, real-time feedback loops, and deep API integrations to streamline workflows.",
    image: "/blog/service-bg.jpg",
    category: "DevTools",
    author: "Team Ignot",
    date: "Jun 5, 2025",
  },
  {
    slug: "seo-for-local-businesses",
    title: "Local SEO Tactics That Drive Real Results",
    desc: "From Google Business Profile optimization to local backlinks and map pack dominance, this guide shows small businesses how to improve visibility in their neighborhoods and rank higher in local search results.",
    image: "/blog/doctor5.png",
    category: "SEO",
    author: "Team Ignot",
    date: "May 18, 2025",
  },
  {
    slug: "ai-for-customer-support",
    title: "Using AI to Automate Customer Support",
    desc: "Discover how integrating AI chatbots, intent detection, and dynamic FAQ builders can save hundreds of support hours monthly. Learn how we used NLP to enhance resolution accuracy and improve customer satisfaction scores.",
    image: "/blog/cba.png",
    category: "AI",
    author: "Team Ignot",
    date: "May 1, 2025",
  },
  {
    slug: "ui-trends-2025",
    title: "Top UI Trends to Watch in 2025",
    desc: "Explore the latest in UI design including neumorphism, AI-powered personalization, micro-interactions, and variable typography. Learn how modern apps use animations and accessibility-first design to engage users.",
    image: "/blog/abc.png",
    category: "UI/UX",
    author: "Team Ignot",
    date: "Apr 10, 2025",
  },
  {
    slug: "devops-for-startups",
    title: "DevOps Playbook for High-Growth Startups",
    desc: "Deploy faster and scale smoother with our DevOps guide tailored for lean startup teams. Learn to set up GitHub Actions, containerize with Docker, and monitor performance using lightweight observability stacks.",
    image: "/blog/abc.png",
    category: "DevTools",
    author: "Team Ignot",
    date: "Mar 28, 2025",
  },
];