export const projects = [
  {
    title: "AI Assistant Bot",
    slug: "ai-assistant-bot",
    type: "AI",
    image: "/images/ai-bot.jpg",
    description: "Conversational AI tool for support & automation.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "EduMentor LMS",
    slug: "edumentor-lms",
    type: "SaaS",
    image: "/portfolio/edtech.jpg",
    description: "Online learning management system for EdTech.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "HealthTrack App",
    slug: "healthtrack-app",
    type: "Mobile",
    image: "/portfolio/health-app.jpg",
    description: "Patient tracking mobile app with alerts & health logs.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "Brand Website for Clinix",
    slug: "brand-website-for-clinix",
    type: "Web",
    image: "/portfolio/clinic-site.jpg",
    description: "Marketing & appointment website for a health brand.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "IG-Commerce",
    slug: "ig-commerce",
    type: "SaaS",
    image: "/portfolio/ecommerce.jpg",
    description: "Scalable e-commerce SaaS for retailers.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "FoodieHub",
    slug: "foodiehub",
    type: "Mobile",
    image: "/portfolio/food-delivery.jpg",
    description: "Food delivery and restaurant management mobile app.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "TaskFlow",
    slug: "taskflow",
    type: "Web",
    image: "/portfolio/project-management.jpg",
    description: "Project management dashboard for teams.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "FinTrack",
    slug: "fintrack",
    type: "SaaS",
    image: "/portfolio/finance.jpg",
    description: "Finance tracking platform for budgeting and expense reports.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "ChatLink",
    slug: "chatlink",
    type: "AI",
    image: "/portfolio/chatbot.jpg",
    description: "AI-powered chatbot for business communication.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "EcoDrive",
    slug: "ecodrive",
    type: "Mobile",
    image: "/portfolio/eco-drive.jpg",
    description: "App promoting eco-friendly driving habits.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "ShopMaster",
    slug: "shopmaster",
    type: "SaaS",
    image: "/portfolio/shop-master.jpg",
    description: "Retail POS and inventory management system.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "TravelGo",
    slug: "travelgo",
    type: "Web",
    image: "/portfolio/travel-site.jpg",
    description: "Tour booking and travel itinerary website.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "FitLife",
    slug: "fitlife",
    type: "Mobile",
    image: "/portfolio/fitness-app.jpg",
    description: "Workout tracking and personalized fitness coaching app.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "Newsly",
    slug: "newsly",
    type: "Web",
    image: "/portfolio/news-portal.jpg",
    description: "News portal with AI-based article recommendations.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "MediConnect",
    slug: "mediconnect",
    type: "SaaS",
    image: "/portfolio/medical-platform.jpg",
    description: "Healthcare SaaS platform for hospitals and clinics.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "SkillUp",
    slug: "skillup",
    type: "Web",
    image: "/portfolio/skills-platform.jpg",
    description: "Online skill development and training platform.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "Eventify",
    slug: "eventify",
    type: "Mobile",
    image: "/portfolio/event-app.jpg",
    description: "Event booking and ticket management mobile app.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "DocuSign Pro",
    slug: "docusign-pro",
    type: "SaaS",
    image: "/portfolio/digital-sign.jpg",
    description: "Digital document signing and management tool.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "MarketPulse",
    slug: "marketpulse",
    type: "AI",
    image: "/images/projects/abc.png",
    description: "AI-driven market analytics and insights dashboard.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "AutoFleet Manager",
    slug: "autofleet-manager",
    type: "Web",
    image: "/portfolio/fleet-management.jpg",
    description: "Fleet tracking and logistics management platform.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "Learnly Kids",
    slug: "learnly-kids",
    type: "Mobile",
    image: "/portfolio/kids-learning.jpg",
    description: "Educational app for kids with gamified lessons.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "CloudDocs",
    slug: "clouddocs",
    type: "SaaS",
    image: "/portfolio/cloud-storage.jpg",
    description: "Cloud-based document storage and collaboration service.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "VisionAI",
    slug: "visionai",
    type: "AI",
    image: "/portfolio/computer-vision.jpg",
    description: "AI computer vision tool for image recognition.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
  {
    title: "BuildWise",
    slug: "buildwise",
    type: "Web",
    image: "/portfolio/construction.jpg",
    description: "Construction project management and estimation site.",
    github: "https://github.com/",
    live: "https://www.google.com",
  },
];
